# Generated by Django 2.0.5 on 2018-11-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181114_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
