# Generated by Django 2.0.5 on 2018-11-14 21:13

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('users', '0005_auto_20181114_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='skill',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='users.TaggedSkill', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='taggedskill',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Skill'),
        ),
        migrations.AddField(
            model_name='taggedskill',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_taggedskill_items', to='taggit.Tag'),
        ),
    ]
