# Generated by Django 2.0.5 on 2018-11-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181114_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='skills',
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='users.Skill'),
        ),
    ]
