# Generated by Django 2.0.5 on 2018-11-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181114_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='skills',
        ),
    ]
