# Generated by Django 2.0.5 on 2018-11-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20181115_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
    ]
