# Generated by Django 2.0.5 on 2018-11-15 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20181115_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='users',
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
