# Generated by Django 2.0.5 on 2018-11-15 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20181115_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='skills',
        ),
        migrations.AddField(
            model_name='newskill',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newskill',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='users.Skill'),
        ),
        migrations.AddField(
            model_name='newskill',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
