# Generated by Django 2.0.5 on 2018-11-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20181115_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newskill',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='newskill',
            name='newskills',
        ),
        migrations.RemoveField(
            model_name='newskill',
            name='users',
        ),
        migrations.DeleteModel(
            name='NewSkill',
        ),
    ]
