# Generated by Django 2.0.5 on 2018-11-16 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20181116_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skills',
            field=models.ManyToManyField(default='', null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
