# Generated by Django 2.0.5 on 2018-11-16 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20181116_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='skills',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
