# Generated by Django 2.0.5 on 2018-11-16 21:45

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('users', '0023_auto_20181116_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='skills',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='users.TaggedSkill', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
