# Generated by Django 2.0.5 on 2018-11-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20181116_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
