# Generated by Django 2.0.5 on 2018-11-17 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20181117_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedskill',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedskill',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='TaggedSkill',
        ),
    ]
