# Generated by Django 2.0.5 on 2018-11-17 04:19

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('users', '0030_skill_taggedskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='users.TaggedSkill', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
