# Generated by Django 2.0.5 on 2018-11-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_customuser_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tags',
        ),
    ]
