# Generated by Django 2.0.5 on 2018-11-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20181117_0518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tags',
            new_name='skills',
        ),
    ]
