# Generated by Django 2.0.5 on 2018-12-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20181204_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skill_area1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skill_area2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skill_area3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skill_area4',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skill_area5',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
