# Generated by Django 2.0.5 on 2018-12-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20181204_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='availability',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rate',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='software_hardware',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
