# Generated by Django 2.1.3 on 2018-12-29 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title/subject of your video call', max_length=200, null=True)),
                ('start_time', models.DateTimeField(null=True, verbose_name='Start time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='End time')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_confirmed', models.BooleanField(blank=True, default=False)),
                ('is_tutorial', models.BooleanField(blank=True, default=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('expert', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
